In [35]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm

import random

import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from keras.metrics import categorical_accuracy

import pickle

In [12]:
DATADIR = "C:/Users/gerar/Desktop/UIDE/TratamientoDatos/examenFinal/ExamenManejoDatos/CarneDataset/test"
CATEGORIES = ["CLASS_01","CLASS_02","CLASS_03","CLASS_04","CLASS_05","CLASS_06","CLASS_07","CLASS_08"]

training_data = []

for category in CATEGORIES:  # read each category
    path = os.path.join(DATADIR,category)  # create path for each category
    class_num = CATEGORIES.index(category)  # get the classification 
    
    for img in tqdm(os.listdir(path)):  # iterate over each image per dogs and cats
            try:
                img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_GRAYSCALE)  # convert to array
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize to normalize data size
                training_data.append([new_array, class_num])  # add this to our training_data
            except Exception as e:  # in the interest in keeping the output clean...
                pass


100%|█████████████████████████████████████████████████████████████████████████████████| 27/27 [00:00<00:00, 102.60it/s]


In [17]:
random.shuffle(training_data)

In [29]:
X = []
y = []

for features,label in training_data:
    X.append(features)
    y.append(label)

print(X[0].reshape(-1, IMG_SIZE, IMG_SIZE, 1))

X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y = np.array(y)

[[[[202]
   [189]
   [188]
   ...
   [  3]
   [  3]
   [  4]]

  [[187]
   [187]
   [187]
   ...
   [  2]
   [  2]
   [  3]]

  [[185]
   [188]
   [187]
   ...
   [  2]
   [  2]
   [  2]]

  ...

  [[112]
   [ 83]
   [108]
   ...
   [ 32]
   [ 47]
   [ 41]]

  [[ 99]
   [ 88]
   [ 74]
   ...
   [ 60]
   [ 35]
   [ 39]]

  [[ 89]
   [104]
   [ 87]
   ...
   [ 65]
   [ 38]
   [ 31]]]]


In [30]:
pickle_out = open("X.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle","wb")
pickle.dump(y, pickle_out)
pickle_out.close()

In [36]:
pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)

X = X/255.0

model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors

model.add(Dense(64))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=[categorical_accuracy])

model.fit(X, y, batch_size=32, epochs=3, validation_split=0.3)

Epoch 1/3
18/18 [==============================] - 51s 3s/step - loss: -30063.2344 - categorical_accuracy: 1.0000 - val_loss: -154312.4219 - val_categorical_accuracy: 1.0000
Epoch 2/3
18/18 [==============================] - 55s 3s/step - loss: -846903.0625 - categorical_accuracy: 1.0000 - val_loss: -2325948.5000 - val_categorical_accuracy: 1.0000
Epoch 3/3
18/18 [==============================] - 56s 3s/step - loss: -6449223.5000 - categorical_accuracy: 1.0000 - val_loss: -13575791.0000 - val_categorical_accuracy: 1.0000
